services:
  php:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 80:80
      volumes:
        - .:/var/www/html/
      environment:
        - compose=true
  
  mariadb:
      image: mariadb:latest
      container_name: mariadb
      restart: always
      environment:
        MYSQL_USER: mariadb
        MYSQL_PASSWORD: mariadb
        MYSQL_DATABASE: mariadb
        MARIADB_ROOT_PASSWORD: todo-ida
      ports:
        - 3306:3306
      volumes:
        - ./src/seed:/docker-entrypoint-initdb.d:ro

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mariadb_data:
